# JupyterHub config for the Positron docker-compose deployment template.
# The Docker analogue of the inline config generated by
# scripts/install-positron.sh. Values come from the environment (see .env /
# docker-compose.yml) so the same image works for any deployment.
import os

verifier_port = os.environ.get("VERIFIER_PORT", "10101")
singleuser_image = os.environ.get("SINGLEUSER_IMAGE", "jupyter-positron-singleuser:latest")
docker_network = os.environ.get("DOCKER_NETWORK", "jupyter-positron")
activation_arch = os.environ.get("POSITRON_ACTIVATION_ARCH", "x86_64")
positron_server_dir = os.environ.get("POSITRON_SERVER_DIR", "/opt/positron-server")

signing_key_file = "/etc/positron/signing-key.pem"
activation_dir = f"{positron_server_dir}/resources/activation/linux/{activation_arch}"
license_file = f"{activation_dir}/license.lic"
license_manager = f"{activation_dir}/license-manager"
minting_endpoint = f"http://hub:{verifier_port}/services/positron-license/mint"

# --- 0. Fail fast if secrets are missing ------------------------------------
# A missing bind-mount source makes Docker create an EMPTY DIRECTORY at the
# target, so a forgotten secret would otherwise surface much later as a cryptic
# mint-time failure. Check at hub boot instead and stop with a clear message.
for _label, _path in (("signing key", signing_key_file), ("license", license_file)):
    if not os.path.isfile(_path) or os.path.getsize(_path) == 0:
        raise RuntimeError(
            f"Positron {_label} not found or empty at {_path}. Add it to "
            "./secrets/ before `docker compose up` (see docker/README.md). "
            "Request a signing key + license from academic-licenses@posit.co."
        )

# --- 1. positron-license minting service ------------------------------------
# Runs in the Hub container, holds the signing key, mints per-session tokens.
# Bind on 0.0.0.0 (not 127.0.0.1 as in TLJH) so single-user containers on the
# docker network can reach it by the hub's service name.
c.JupyterHub.services = [
    {
        "name": "positron-license",
        "url": f"http://0.0.0.0:{verifier_port}",
        "command": ["positron-verifier"],
        "environment": {
            "POSITRON_MINTING_KEY_FILE": signing_key_file,
            "POSITRON_LICENSE_MANAGER_PATH": license_manager,
            "PORT": verifier_port,
        },
    }
]

c.JupyterHub.load_roles = [
    {
        "name": "positron-license-service",
        "services": ["positron-license"],
        "scopes": ["read:users"],
    }
]

# --- 2. DockerSpawner: launch single-user containers as siblings ------------
c.JupyterHub.spawner_class = "dockerspawner.DockerSpawner"
c.DockerSpawner.image = singleuser_image
c.DockerSpawner.network_name = docker_network
c.DockerSpawner.use_internal_ip = True
c.DockerSpawner.remove = True  # remove stopped single-user containers

# The Hub API must be reachable by the spawned containers: bind on all
# interfaces, and have containers connect back by the compose service name.
c.JupyterHub.hub_ip = "0.0.0.0"
c.JupyterHub.hub_connect_ip = "hub"

# Session environment: only the minting endpoint. PATH is intentionally NOT set
# here — positron-server is already on PATH via the single-user image's ENV, and
# overriding PATH would drop the image's own entries.
c.DockerSpawner.environment = {
    "POSITRON_LICENSE_MINTING_ENDPOINT": minting_endpoint,
}

# --- 3. Authenticator -------------------------------------------------------
# !!! TEMPLATE PLACEHOLDER: DummyAuthenticator accepts ANY username with ANY
# !!! password. You MUST replace this with a real authenticator (OAuth, native,
# !!! LDAP, ...) before any non-local or real deployment.
c.JupyterHub.authenticator_class = "jupyterhub.auth.DummyAuthenticator"
