# JupyterHub config for the Positron docker-compose deployment template.
# The Docker analogue of the inline config generated by
# scripts/install-positron.sh. Values come from the environment (see .env /
# docker-compose.yml) so the same image works for any deployment.
import os

singleuser_image = os.environ.get("SINGLEUSER_IMAGE", "jupyter-positron-singleuser:latest")
docker_network = os.environ.get("DOCKER_NETWORK", "jupyter-positron")
activation_arch = os.environ.get("POSITRON_ACTIVATION_ARCH", "x86_64")
positron_server_dir = os.environ.get("POSITRON_SERVER_DIR", "/opt/positron-server")
license_host_path = os.environ.get("POSITRON_LICENSE_HOST_PATH", "")

activation_dir = f"{positron_server_dir}/resources/activation/linux/{activation_arch}"

# --- 0. Fail fast if the license secret is missing --------------------------
# A missing bind-mount source makes Docker create an EMPTY DIRECTORY at the
# target, so a forgotten secret would otherwise surface much later as a
# cryptic per-session failure. Check at hub boot instead and stop with a clear
# message.
#
# This mount (/run/secrets/license.lic, below) exists in THIS container only
# for this check. The file single-user sessions actually read is bind-mounted
# separately by DockerSpawner in step 1, from POSITRON_LICENSE_HOST_PATH.
_check_path = "/run/secrets/license.lic"
if not os.path.isfile(_check_path) or os.path.getsize(_check_path) == 0:
    raise RuntimeError(
        f"Positron license not found or empty at {_check_path}. Add it to "
        "./secrets/license.lic before `docker compose up` (see docker/README.md). "
        "Request one from academic-licenses@posit.co."
    )
if not license_host_path:
    raise RuntimeError(
        "POSITRON_LICENSE_HOST_PATH is not set. It must be the absolute path, "
        "on the Docker host (not inside this container), to secrets/license.lic "
        "-- see docker-compose.yml."
    )

# --- 1. DockerSpawner: launch single-user containers as siblings ------------
c.JupyterHub.spawner_class = "dockerspawner.DockerSpawner"
c.DockerSpawner.image = singleuser_image
c.DockerSpawner.network_name = docker_network
c.DockerSpawner.use_internal_ip = True
c.DockerSpawner.remove = True  # remove stopped single-user containers

# The license file, mounted read-only at the exact path positron-server
# validates itself, in each session's activation directory. DockerSpawner
# talks to the HOST docker daemon (via the socket mounted into this
# container), so the mount source must be a host-absolute path, not a path
# inside this container -- hence POSITRON_LICENSE_HOST_PATH rather than the
# ./secrets/license.lic mount used for the check above.
c.DockerSpawner.volumes = {
    license_host_path: {"bind": f"{activation_dir}/license.lic", "mode": "ro"},
}

# The Hub API must be reachable by the spawned containers: bind on all
# interfaces, and have containers connect back by the compose service name.
c.JupyterHub.hub_ip = "0.0.0.0"
c.JupyterHub.hub_connect_ip = "hub"

# No POSITRON_* environment variable is needed: positron-server finds and
# validates the mounted license file in its own activation directory. PATH is
# intentionally NOT set here -- positron-server is already on PATH via the
# single-user image's ENV, and overriding PATH would drop the image's own
# entries.

# --- 2. Authenticator -------------------------------------------------------
# !!! TEMPLATE PLACEHOLDER: DummyAuthenticator accepts ANY username with ANY
# !!! password. You MUST replace this with a real authenticator (OAuth, native,
# !!! LDAP, ...) before any non-local or real deployment.
c.JupyterHub.authenticator_class = "jupyterhub.auth.DummyAuthenticator"
